# Generated by Django 2.2.8 on 2020-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('date_Started', models.DateField(blank=True, null=True)),
                ('reg_Link', models.CharField(blank=True, max_length=200)),
                ('club_Link', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
