# Generated by Django 2.2.8 on 2020-03-26 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
        ('Clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clubs',
            new_name='Club',
        ),
        migrations.CreateModel(
            name='IsIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clubs.Club')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.User')),
            ],
        ),
    ]
