# Generated by Django 2.2.8 on 2020-03-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
        ('Clubs', '0002_auto_20200327_0108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IsIn',
            new_name='Club_Members',
        ),
    ]
