# Generated by Django 2.2.8 on 2020-03-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0003_auto_20200327_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club_Members',
        ),
    ]
