# Generated by Django 2.2.8 on 2020-04-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
        ('Clubs', '0003_remove_club_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='projects',
            field=models.ManyToManyField(to='Projects.Project'),
        ),
    ]
