# Generated by Django 2.2.8 on 2020-03-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20200327_0110'),
        ('Main', '0004_auto_20200329_0116'),
        ('Clubs', '0004_delete_club_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(to='Main.User'),
        ),
        migrations.AddField(
            model_name='club',
            name='projects',
            field=models.ManyToManyField(to='Projects.Project'),
        ),
    ]
