# Generated by Django 2.2.8 on 2020-03-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20200329_0116'),
        ('Clubs', '0005_auto_20200329_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='club_name',
            new_name='club_Name',
        ),
        migrations.RemoveField(
            model_name='club',
            name='members',
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_Type', models.CharField(max_length=20)),
                ('date_Joined', models.DateField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clubs.Club')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.User')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='member',
            field=models.ManyToManyField(through='Clubs.Members', to='Main.User'),
        ),
    ]
