# Generated by Django 2.2.8 on 2020-03-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0007_auto_20200330_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_Link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='club',
            name='date_Started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='reg_Link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='members',
            name='date_Joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
