# Generated by Django 2.2.8 on 2020-03-31 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0008_auto_20200330_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='member',
            field=models.ManyToManyField(through='Clubs.Members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='members',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
