# Generated by Django 2.2.8 on 2020-03-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20200328_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_Address',
            new_name='email_Adress',
        ),
    ]
