# Generated by Django 2.2.8 on 2020-03-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20200328_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_Adress',
            new_name='email_Address',
        ),
    ]
