# Generated by Django 2.2.8 on 2020-04-20 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_Name', models.CharField(max_length=100)),
                ('date_Started', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('working_Users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
