# Generated by Django 2.2.8 on 2020-03-30 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_project_working_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_Started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
